#!/usr/bin/env bash
# Information about the domain
domain_info() {
    record=$(dig $2.$1 | grep -A1 'ANSWER SECTION:' | awk '{print $4}')
    ip=$(dig $2.$1 | grep -A1 'ANSWER SECTION:' | awk '{print $5}')
    echo "The subdomain $2 is a $record record and points to $ip"
    
	return 0
}

# Entry point
# if only variable $1 (DOMAIN name)
if [ -z "$2" ]
then
    # print info for all submodules
    domain_info "$1" "www"
    domain_info "$1" "lb-01"
    domain_info "$1" "web-01"
    domain_info "$1" "web-02"
else
    # print info for subdomain in $SUBDOMAIN
    domain_info "$1" "$2"
fi
