#!/usr/bin/env bash
# Information about the domain
domain_info() {
SUBDOMAIN=$1
DOMAIN=$2
    RECORD=$(dig $SUBDOMAIN.$DOMAIN | awk '/ANSWER SECTION/{getline; print}' | awk '{print $4}')
    IP=$(dig $SUBDOMAIN.$DOMAIN | awk '/ANSWER SECTION/{getline; print}' | awk '{print $5}')
    echo "The subdomain $SUBDOMAIN is a $RECORD record and points to $IP"
    }


DOMAIN=$1
SUBDOMAIN=$2
# Entry point
# if only variable $1 (DOMAIN name)
if [ -z "$SUBDOMAIN" ]
then
    # print info for all submodules
    domain_info "www" "$DOMAIN"
    domain_info "lb-01" "$DOMAIN"
    domain_info "web-01" "$DOMAIN"
    domain_info "web-02" "$DOMAIN"
else
    # print info for subdomain in $SUBDOMAIN
    domain_info "$SUBDOMAIN" "$DOMAIN"
fi