#!/usr/bin/env bash
# Information about the domain
domain_info() {
    RECORD=$(dig $2.$1 | awk '/ANSWER SECTION/{getline; print}' | awk '{print $4}')
    IP=$(dig $2.$1 | awk '/ANSWER SECTION/{getline; print}' | awk '{print $5}')
    echo "The subdomain $SUBDOMAIN is a $RECORD record and points to $IP"
    
	return 0
	}

# Entry point
# if only variable $1 (DOMAIN name)
if [ -z "$SUBDOMAIN" ]
then
    # print info for all submodules
    domain_info "$1" "www"
    domain_info "$1" "lb-01"
    domain_info "$1" "web-01"
    domain_info "$1" "web-02"
else
    # print info for subdomain in $SUBDOMAIN
    domain_info "$1" "$2"
fi
