#!/usr/bin/env bash
# instal nginx and set up index.html

sudo apt-get update
sudo apt-get install -y nginx
echo "Holberton School for the win!" | sudo tee /var/www/html/index.html
sudo service nginx start
