#!/usr/bin/env bash
# Install nginx and redirect 301 (moved permantly)
sudo apt-get update
sudo apt-get install -y nginx
echo "Holberton School" | sudo tee /var/www/html/index.html
newtext="rewrite ^/redirect_me https://www.youtube.com/watch?v=jyknCVczn3Q permanent;"
sudo sed -i "/listen 80 default_server/a $newtext" /etc/nginx/sites-available/default
sudo service nginx start
