#!/usr/bin/env bash
# Install nginx and redirect 301 (moved permantly)
sudo apt -y update
sudo apt -y install nginx
sudo echo "Holberton School" | sudo tee /var/www/html/index.html
sudo sed -i "/listen 80 default_server;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;" /etc/nginx/sites-available/default
sudo service nginx start
