#!/usr/bin/env bash
#This will redirect permanently
sudo apt-get update
sudo apt-get -y install nginx
echo "Holberton School" >> /var/www/html/index.html
echo "Ceci n'est pas une page" >> sudo /var/www/html/custom_404.html
sudo sed -i "/^\tlocation \// i\ \tlocation /redirect_me {\n\t\treturn 301 https://facebook.com;\n\t}" /etc/nginx/sites-enabled/default
sudo sed -i '/error_page 404 /custom_404.html;\nlocation = /custom_404.html {\nroot /var/www/html;\ninternal;\n}\n' /etc/nginx/sites-enabled/default
sudo service nginx restart
