#!/usr/bin/env bash
#onfigure Nginx so that its HTTP response contains a custom header (on web-01 and web-02)
sudo apt-get update
sudo apt-get install -y nginx
echo "Holberton School for the win!" | sudo tee /var/www/html/index.html
sudo echo "Ceci n'est pas une page" | sudo tee /var/www/html/custom_404.html
if ! grep -q "add_header X-Served-By" /etc/nginx/nginx.conf; then
	sudo sed -i "s/http {/http {\n\tadd_header X-Served-By \$hostname;dd_header X-Served-By \$hostname;/" /etc/nginx/nginx.conf
fi
sudo service nginx start
