#!/usr/bin/env bash
# a script that installs and configures HAproxy
sudo apt-get update -y && sudo apt-get install -y haproxy=1.6.\*
echo -e "frontend haproxynode\n\tbind *:80" >> /etc/haproxy/haproxy.cfg
echo -e "\tmode http\n\tdefault_backend web-backend" >> /etc/haproxy/haproxy.cfg
echo -e "backend web-backend\n\tbalance roundrobin" >> /etc/haproxy/haproxy.cfg
echo -e "\tserver 1162-web-01 34.74.164.242:80 check\n" >> /etc/haproxy/haproxy.cfg
echo -e "\tserver 1162-web-02 3.87.108.35:80 check\n" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
