#!/usr/bin/env bash
# a script that installs and configures HAproxy
apt-get update -y && apt-get install -y haproxy
lb_config="backend web-backend\n\tbalance roundrobin\n\tserver 1162-web-01 34.74.164.242:80 check\n\tserver 1162-web-02 3.87.108.35:80check\n\nfrontend http\n\tbind *:80\n\tmode http\n\tdefault_backend web-backend"
sudo echo -ne "$lb_config" >> /etc/haproxy/haproxy.cfg
service haproxy restart
