#!/usr/bin/env bash
# script to fix nginx server that won't shut off via daemon manager
sudo mv /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo cp /etc/nginx/sites-enabled/default /etc/nginx/sites-available/default 
service nginx stop
pkill nginx
service nginx start
