#!/usr/bin/env bash
# Fix this container so that Nginx is running as the nginx user.
sudo pkill apache2
sudo chmod 755 /etc/nginx/nginx.conf
sudo sed -i "s/80/8080/" /etc/nginx/sites-enabled/default
sudo sed -i 's/#user www-data;/user nginx;/' /etc/nginx/nginx.conf
sudo -u nginx service nginx restart
