#!/usr/bin/env bash
#a script to run nginx as nginx
pkill 
sudo chmod 777 /etc/nginx/nginx.conf
sed -i 's/listen 80 default_server;/listen 8080 default_server;/' /etc/nginx/sites-available/default
sed -i 's/listen \[::\]:80 default_server ipv6only=on;/listen \[::\]:8080 default_server ipv6only=on;/' /etc/nginx/sites-available/default
sudo -u nginx service nginx start
